# action.yml
name: YouTube Thumbnail Downloader
description: Downloads a YouTube thumbnail from a video URL
inputs:
  url:
    description: 'YouTube video URL'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        url="${{ inputs.url }}"
        id=$(echo "$url" | cut -d '=' -f2)
        filename="$id.jpg"
        curl -o "$filename" "https://img.youtube.com/vi/$id/maxresdefault.jpg"
      shell: bash